# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33975e7ea9794e0865a4cdb8849a5861279fe4fba1a5c0a1c5288ebcd1056b000dfdab5ab26b632beba1228bfe1709a4fa705127e27009c6576b6e2b9efb21cc

test:
  secret_key_base: fb92e4488be16950c6c6931331c0aa5e407e90fa8eb79f33db9a1c701209ea4be0248084c68c971b544d9a44cbebc9826d7fd3cd54098453f550e0860dfdc436

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
